project:
  type: website
website:
  title: "blog"
  site-url: "https://charming-souffle-80cbc8.netlify.app"
  site-path: "/"
  cookie-consent:
    type: express
    style: headline
    palette: dark
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: default
    css: styles.css
    include-in-header:
     - file: analytics.html
execute:
  freeze: auto


